<?php // this is an autogenerated file - do not edit (created 2009-12-14 15:38:39)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'spriebsch\\mvc\\applicationcontrollertest' => 'ApplicationControllerTest.php',
         'spriebsch\\mvc\\test\\testviewhelper' => '_testdata/ViewHelper/TestViewHelper.php',
         'spriebsch\\mvc\\test\\frontcontroller\\authentication' => '_testdata/FrontController/Authentication.php',
         'spriebsch\\mvc\\test\\frontcontroller\\authenticationexecutedexception' => '_testdata/FrontController/Authentication.php',
         'spriebsch\\mvc\\test\\frontcontroller\\action' => '_testdata/FrontController/Action.php',
         'spriebsch\\mvc\\test\\frontcontroller\\actionexecutedexception' => '_testdata/FrontController/Action.php',
         'spriebsch\\mvc\\test\\frontcontroller\\testfc' => '_testdata/FrontController/TestFC.php',
         'spriebsch\\mvc\\test\\frontcontroller\\controller' => '_testdata/FrontController/Controller.php',
         'spriebsch\\mvc\\test\\twoactionscontroller' => '_testdata/Controller/TwoActionsController.php',
         'spriebsch\\mvc\\test\\someactionexecutedexception' => '_testdata/Controller/TwoActionsController.php',
         'spriebsch\\mvc\\test\\notallowedcontroller' => '_testdata/Controller/NotAllowedController.php',
         'spriebsch\\mvc\\test\\redirectcontroller' => '_testdata/Controller/RedirectController.php',
         'spriebsch\\mvc\\test\\defaultactioncontroller' => '_testdata/Controller/DefaultActionController.php',
         'spriebsch\\mvc\\test\\defaultactionexecutedexception' => '_testdata/Controller/DefaultActionController.php',
         'spriebsch\\mvc\\test\\setviewnamecontroller' => '_testdata/Controller/SetViewNameController.php',
         'spriebsch\\mvc\\responsetest' => 'ResponseTest.php',
         'spriebsch\\mvc\\messagetest' => 'MessageTest.php',
         'spriebsch\\mvc\\formerrorstest' => 'ViewHelper/FormErrorsTest.php',
         'spriebsch\\mvc\\ultest' => 'ViewHelper/UlTest.php',
         'spriebsch\\mvc\\urltest' => 'ViewHelper/UrlTest.php',
         'spriebsch\\mvc\\mocksessiontest' => 'MockSessionTest.php',
         'spriebsch\\mvc\\tabledatagatewaytest' => 'TableDataGatewayTest.php',
         'spriebsch\\mvc\\viewtest' => 'ViewTest.php',
         'spriebsch\\mvc\\acltest' => 'AclTest.php',
         'spriebsch\\mvc\\viewhelpertest' => 'ViewHelperTest.php',
         'spriebsch\\mvc\\controllertest' => 'ControllerTest.php',
         'spriebsch\\mvc\\sessiontest' => 'SessionTest.php',
         'spriebsch\\mvc\\routertest' => 'RouterTest.php',
         'spriebsch\\mvc\\requesttest' => 'RequestTest.php',
         'spriebsch\\mvc\\frontcontrollertest' => 'FrontControllerTest.php',
         'spriebsch\\mvc\\formerrortest' => 'Message/FormErrorTest.php',
         'spriebsch\\mvc\\fielderrortest' => 'Message/FieldErrorTest.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . '/' .  $classes[$cn];
      }
   }
);
?>
