<?php // this is an autogenerated file - do not edit (created 2009-12-16 17:02:23)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'spriebsch\\mvc\\message' => 'Message.php',
         'spriebsch\\mvc\\session' => 'Session.php',
         'spriebsch\\mvc\\viewfactory' => 'ViewFactory.php',
         'spriebsch\\mvc\\mocksession' => 'MockSession.php',
         'spriebsch\\mvc\\response' => 'Response.php',
         'spriebsch\\mvc\\acl' => 'Acl.php',
         'spriebsch\\mvc\\exception' => 'Exceptions.php',
         'spriebsch\\mvc\\unknownvariableexception' => 'Exceptions.php',
         'spriebsch\\mvc\\routerexception' => 'Exceptions.php',
         'spriebsch\\mvc\\controllerexception' => 'Exceptions.php',
         'spriebsch\\mvc\\frontcontrollerexception' => 'Exceptions.php',
         'spriebsch\\mvc\\sessionexception' => 'Exceptions.php',
         'spriebsch\\mvc\\viewexception' => 'Exceptions.php',
         'spriebsch\\mvc\\viewhelper\\errors' => 'ViewHelper/Errors.php',
         'spriebsch\\mvc\\viewhelper\\formerrors' => 'ViewHelper/FormErrors.php',
         'spriebsch\\mvc\\viewhelper\\menu' => 'ViewHelper/Menu.php',
         'spriebsch\\mvc\\viewhelper\\options' => 'ViewHelper/Options.php',
         'spriebsch\\mvc\\viewhelper\\table' => 'ViewHelper/Table.php',
         'spriebsch\\mvc\\viewhelper\\url' => 'ViewHelper/Url.php',
         'spriebsch\\mvc\\viewhelper\\fielderrors' => 'ViewHelper/FieldErrors.php',
         'spriebsch\\mvc\\viewhelper\\ul' => 'ViewHelper/Ul.php',
         'spriebsch\\mvc\\authenticationadapter' => 'AuthenticationAdapter.php',
         'spriebsch\\mvc\\applicationcontroller' => 'ApplicationController.php',
         'spriebsch\\mvc\\view' => 'View.php',
         'spriebsch\\mvc\\viewhelper' => 'ViewHelper.php',
         'spriebsch\\mvc\\jsonview' => 'JsonView.php',
         'spriebsch\\mvc\\router' => 'Router.php',
         'spriebsch\\mvc\\controller' => 'Controller.php',
         'spriebsch\\mvc\\controllerfactory' => 'ControllerFactory.php',
         'spriebsch\\mvc\\frontcontroller' => 'FrontController.php',
         'spriebsch\\mvc\\request' => 'Request.php',
         'spriebsch\\mvc\\message\\formerror' => 'Message/FormError.php',
         'spriebsch\\mvc\\message\\fielderror' => 'Message/FieldError.php',
         'spriebsch\\mvc\\message\\error' => 'Message/Error.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . '/' .  $classes[$cn];
      }
   }
);
?>
